manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: miketronic
      url-base: https://github.com/miketronic
    - name: m165437
      url-base: https://github.com/M165437
    - name: nuovotaka
      url-base: https://github.com/nuovotaka
    - name: badjeff
      url-base: https://github.com/badjeff
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-keyboards-ataraxia
      remote: miketronic
      revision: ataraxia_v1_qwerty_5col
    - name: nice-view-gem
      remote: m165437
      revision: main
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-pointing-acceleration-alpha
      remote: nuovotaka
      revision: main
  self:
    path: config
