
#
# ataraxia v1
#

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: miketronic
      url-base: https://github.com/miketronic
    - name: nuovotaka
      url-base: https://github.com/nuovotaka

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-keyboards-ataraxia
      remote: miketronic
      revision: f0d76e7dd3b1b078af18263dd4f9d2cd386f75a0
    - name: zmk-pmw3610-driver-02
      remote: miketronic
      revision: main
    - name: zmk-pointing-acceleration-alpha
      remote: miketronic
      revision: main
      
  self:
    path: config

